name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install curl
        brew install gpg


    - name: Build PJSIP
      run: |
        curl -o pjproject-2.10.tar.gz https://codeload.github.com/pjsip/pjproject/tar.gz/2.10
        tar xzvf pjproject-2.10.tar.gz
        cd pjproject-2.10
        echo '#define PJSIP_DONT_SWITCH_TO_TCP 1' >> pjlib/include/pj/config_site.h
        echo '#define PJSUA_MAX_ACC 32' >> pjlib/include/pj/config_site.h
        echo '#define PJMEDIA_RTP_PT_TELEPHONE_EVENTS 101' >> pjlib/include/pj/config_site.h
        echo '#define PJ_DNS_MAX_IP_IN_A_REC 32' >> pjlib/include/pj/config_site.h
        echo '#define PJ_DNS_SRV_MAX_ADDR 32' >> pjlib/include/pj/config_site.h
        echo '#define PJSIP_MAX_RESOLVED_ADDRESSES 32' >> pjlib/include/pj/config_site.h
        echo '#define PJ_HAS_IPV6 1' >> pjlib/include/pj/config_site.h
        # Add build commands for PJSIP here
